server:
  port: 8000
  tomcat:
    max-threads: 40
spring:
  application:
    name: gatewat-service
#  boot:
#    admin:
#      client:
#        name: ${spring.application.name}
#      url: http://localhost:18000

security:
  basic:
    enabled: false
management:
  endpoints:
    web.exposure.include: "*"

  endpoint:
    health:
      show-details: ALWAYS
  security:
    enabled: false
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: gateway-service
#    prefer-ip-address: true

#断路器配置
hystrix.command.default:
  execution.isolation.thread.timeoutInMilliseconds: 32000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 30000
  MaxAutoRetriesNextServer: 0
  MaxAutoRetries: 3
  eureka:
    enabled: false


zuul:
  host:
    socket-timeout-millis: 10000
  #    max-per-route-connections: 2
  routes:
    question-server:
      path: /questions/**
      url: http://wanghe.site
      stripPrefix: true
    service-vehicle-manager:
      path: /vehicles/**
      serviceId: service-vehicle-manager
      #      url: http://localhost:9000
      stripPrefix: false

service-vehicle-manager:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: http://www.baidu.com
logging:
  level:
    root: info
  file: logs/application.log
