server:
  port: 8080
spring:
  application:
    name: queries-service
  datasource:
#    url: jdbc:mysql://106.14.10.251:3306/question_bank?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://127.0.01:3306/question_bank?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.qq.com
    port: 587
    username: 178070584@qq.com
    password: gzuamyhwjhinbjch
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          starttls.required: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

#接收警告邮件的邮箱地址，多个逗号隔开
alarm.email:
  receiver: 178070584@qq.com
  #邮件发送报警间隔时间，默认300秒
  interval.time: 300

logging:
  level:
    root: INFO


api:
  urls:
    host: http://123.15.57.109
    homepageHost: http://123.15.57.122
    testPaperHost: http://123.15.57.74
    loginUrl: http://123.15.57.15/sss/zzjlogin.dll/login
    userInfoUrl: http://171.8.225.154/vls2s/vls3isapi.dll/personalinfo?ptopid={1}
    questionBankLoginUrl: http://222.22.63.178/student/wsdlLogin?ptopid=
    coursesUrl: http://222.22.63.178/student/courseList
    courseQuestionsUrl: http://222.22.63.178/student/courseSelect?studentCourseId={1}
    questionUrl: http://222.22.63.178/student/getQuestion?qId={1}&isSimulate=1
    testPaperUrl: http://123.15.57.74/vls2s/vls3isapi.dll/testonce

